--c.extra_entities = c.extra_entities.."files/gkbrkn/actions/wip/projectile_extra_entity.xml,"
--draw_actions( 1, true );
--add_projectile( "files/gkbrkn/actions/wip/projectile_capture.xml" );
--add_projectile_trigger_hit_world("data/entities/projectiles/deck/light_bullet.xml", 1)
--c.extra_entities = c.extra_entities.."files/gkbrkn/actions/wip/projectile_extra_entity.xml,"
--LogTable( current_action )
--GamePrint(parent );
